// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMVvhEM6XGgbNbVVBbeCu578EHX_cbCtI',
    appId: '1:400396182536:web:2c23903b868608bf049dbd',
    messagingSenderId: '400396182536',
    projectId: 'sylvest-alpha-1-0',
    authDomain: 'sylvest-alpha-1-0.firebaseapp.com',
    storageBucket: 'sylvest-alpha-1-0.appspot.com',
    measurementId: 'G-ZMVXXG9TJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKZql6kCW_T_Tv5RwC_QoY5RGpXYkAVTw',
    appId: '1:400396182536:android:132ccb4b52328966049dbd',
    messagingSenderId: '400396182536',
    projectId: 'sylvest-alpha-1-0',
    storageBucket: 'sylvest-alpha-1-0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4ags2-xSWX9tTEE9sxjrhwCWScoIaGDY',
    appId: '1:400396182536:ios:69bcb0d23d14733f049dbd',
    messagingSenderId: '400396182536',
    projectId: 'sylvest-alpha-1-0',
    storageBucket: 'sylvest-alpha-1-0.appspot.com',
    iosClientId:
        '400396182536-g7atkrvk2m4r1thpo7k6okho6o4eu156.apps.googleusercontent.com',
    iosBundleId: 'com.example.sylvetApp',
  );
}
